import { registerSchema } from "../registry";
import { GGA_SCHEMA } from "./GGA";
import { GSA_SCHEMA } from "./GSA";
import { RMC_SCHEMA } from "./RMC";
import { AAM_SCHEMA } from "./AAM";
import { ABK_SCHEMA } from "./ABK";
import { ABM_SCHEMA } from "./ABM";
import { ACA_SCHEMA } from "./ACA";
import { ACF_SCHEMA } from "./ACF";
import { ACG_SCHEMA } from "./ACG";
import { ACK_SCHEMA } from "./ACK";
import { ACM_SCHEMA } from "./ACM";
import { ACS_SCHEMA } from "./ACS";
import { ADS_SCHEMA } from "./ADS";
import { AFB_SCHEMA } from "./AFB";
import { AGA_SCHEMA } from "./AGA";
import { AID_SCHEMA } from "./AID";
import { AIR_SCHEMA } from "./AIR";
import { AKD_SCHEMA } from "./AKD";
import { ALA_SCHEMA } from "./ALA";
import { ALM_SCHEMA } from "./ALM";
import { ALR_SCHEMA } from "./ALR";
import { APB_SCHEMA } from "./APB";
import { ASN_SCHEMA } from "./ASN";
import { BBM_SCHEMA } from "./BBM";
import { BCG_SCHEMA } from "./BCG";
import { BCL_SCHEMA } from "./BCL";
import { BEC_SCHEMA } from "./BEC";
import { BOD_SCHEMA } from "./BOD";
import { BWC_SCHEMA } from "./BWC";
import { BWR_SCHEMA } from "./BWR";
import { BWW_SCHEMA } from "./BWW";
import { CBR_SCHEMA } from "./CBR";
import { CEK_SCHEMA } from "./CEK";
import { COP_SCHEMA } from "./COP";
import { CPC_SCHEMA } from "./CPC";
import { CPD_SCHEMA } from "./CPD";
import { CPG_SCHEMA } from "./CPG";
import { CPN_SCHEMA } from "./CPN";
import { CPR_SCHEMA } from "./CPR";
import { CPS_SCHEMA } from "./CPS";
import { CPT_SCHEMA } from "./CPT";
import { CUR_SCHEMA } from "./CUR";
import { DBT_SCHEMA } from "./DBT";
import { MTW_SCHEMA } from "./MTW";
import { MWD_SCHEMA } from "./MWD";
import { MWV_SCHEMA } from "./MWV";
import { NAK_SCHEMA } from "./NAK";
import { NRM_SCHEMA } from "./NRM";
import { NRX_SCHEMA } from "./NRX";
import { OSD_SCHEMA } from "./OSD";
import { PRC_SCHEMA } from "./PRC";
import { RMA_SCHEMA } from "./RMA";
import { RMB_SCHEMA } from "./RMB";
import { ROR_SCHEMA } from "./ROR";
import { ROT_SCHEMA } from "./ROT";
import { RPM_SCHEMA } from "./RPM";
import { RSA_SCHEMA } from "./RSA";
import { RSD_SCHEMA } from "./RSD";
import { RST_SCHEMA } from "./RST";
import { RTE_SCHEMA } from "./RTE";
import { SFI_SCHEMA } from "./SFI";
import { SID_SCHEMA } from "./SID";
import { XDR_SCHEMA } from "./XDR";
import { XTR_SCHEMA } from "./XTR";
import { ZDA_SCHEMA } from "./ZDA";
import { ZDL_SCHEMA } from "./ZDL";
import { ZFO_SCHEMA } from "./ZFO";
import { ZTG_SCHEMA } from "./ZTG";
import { TTD_SCHEMA } from "./TTD";
import { SPO_SCHEMA } from "./SPO";
import { SSD_SCHEMA } from "./SSD";
import { STN_SCHEMA } from "./STN";
import { TBR_SCHEMA } from "./TBR";
import { TBS_SCHEMA } from "./TBS";
import { TFR_SCHEMA } from "./TFR";

registerSchema(GGA_SCHEMA);
registerSchema(GSA_SCHEMA);
registerSchema(RMC_SCHEMA);
registerSchema(AAM_SCHEMA);
registerSchema(ABK_SCHEMA);
registerSchema(ABM_SCHEMA);
registerSchema(ACA_SCHEMA);
registerSchema(ACF_SCHEMA);
registerSchema(ACG_SCHEMA);
registerSchema(ACK_SCHEMA);
registerSchema(ACM_SCHEMA);
registerSchema(ACS_SCHEMA);
registerSchema(ADS_SCHEMA);
registerSchema(AFB_SCHEMA);
registerSchema(AGA_SCHEMA);
registerSchema(AID_SCHEMA);
registerSchema(AIR_SCHEMA);
registerSchema(AKD_SCHEMA);
registerSchema(ALA_SCHEMA);
registerSchema(ALM_SCHEMA);
registerSchema(ALR_SCHEMA);
registerSchema(APB_SCHEMA);
registerSchema(ASN_SCHEMA);
registerSchema(BBM_SCHEMA);
registerSchema(BCG_SCHEMA);
registerSchema(BCL_SCHEMA);
registerSchema(BEC_SCHEMA);
registerSchema(BOD_SCHEMA);
registerSchema(BWC_SCHEMA);
registerSchema(BWR_SCHEMA);
registerSchema(BWW_SCHEMA);
registerSchema(CBR_SCHEMA);
registerSchema(CEK_SCHEMA);
registerSchema(COP_SCHEMA);
registerSchema(CPC_SCHEMA);
registerSchema(CPD_SCHEMA);
registerSchema(CPG_SCHEMA);
registerSchema(CPN_SCHEMA);
registerSchema(CPR_SCHEMA);
registerSchema(CPS_SCHEMA);
registerSchema(CPT_SCHEMA);
registerSchema(CUR_SCHEMA);
registerSchema(DBT_SCHEMA);
registerSchema(MTW_SCHEMA);
registerSchema(MWD_SCHEMA);
registerSchema(MWV_SCHEMA);
registerSchema(NAK_SCHEMA);
registerSchema(NRM_SCHEMA);
registerSchema(NRX_SCHEMA);
registerSchema(OSD_SCHEMA);
registerSchema(PRC_SCHEMA);
registerSchema(RMA_SCHEMA);
registerSchema(RMB_SCHEMA);
registerSchema(ROR_SCHEMA);
registerSchema(ROT_SCHEMA);
registerSchema(RPM_SCHEMA);
registerSchema(RSA_SCHEMA);
registerSchema(RSD_SCHEMA);
registerSchema(RST_SCHEMA);
registerSchema(RTE_SCHEMA);
registerSchema(SFI_SCHEMA);
registerSchema(SID_SCHEMA);
registerSchema(XDR_SCHEMA);
registerSchema(XTR_SCHEMA);
registerSchema(ZDA_SCHEMA);
registerSchema(ZDL_SCHEMA);
registerSchema(ZFO_SCHEMA);
registerSchema(ZTG_SCHEMA);
registerSchema(TTD_SCHEMA);
registerSchema(SPO_SCHEMA);
registerSchema(SSD_SCHEMA);
registerSchema(STN_SCHEMA);
registerSchema(TBR_SCHEMA);
registerSchema(TBS_SCHEMA);
registerSchema(TFR_SCHEMA);
